build:
  version: "3.0"

products:
  message: "Welcome to ecart products related docker APIs "
  contactDetails:
    name: "venkatesh - Developer"
    email: "venky@ecart.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
